### ISSUE TITLE
Reliability issues and other related requests

### ISSUE THREAD

**Issue by carolineemueller** [miyamot0/DataTracker3#1]
I have encountered a few issues with the current version of Data Tracker.

The program often quits when reliability is calculated. When the program does not quit, the reliability output generated only reflects scores for the frequency keys (not duration keys). It also appears that data streams are being compared based off the time stamps of recorded keys. It would be helpful if the files were compared based on the start times instead, so a session could be coded from a video at a later time and compared to the primary file. 

After collecting data, the program asks if the user would like to discard the data, with the default answer being 'yes'. Could you change the program to ask if the user would like to save the data (to make accidentally deleting files less likely)? 

Also, are we able to change the primary save location on Data Tracker from the computer to Dropbox? This would allow us to calculate reliability without having to manually move all files onto one computer.

**Comment by miyamot0** [comment]
Closed. Commit: [3803c6de5e9e6479fe350ab3a61f37669ab49e54](https://github.com/miyamot0/DataTracker3/commit/3803c6de5e9e6479fe350ab3a61f37669ab49e54)
