### ISSUE TITLE
Calculating Reliability 

### ISSUE THREAD

**Issue by ea9872** [miyamot0/DataTracker3#4]
With two different duration keys, each time I calculate a reliability report between two data collectors, each key has the exact partial interval agreement (for example, if key F denotes one behavior and key L denotes another, Data Tracker is calculating 85.67 PIA for both keys although the behaviors for these two keys are not occurring at similar rates). In addition, after calculating reliability by hand I was not able to get the same agreement- can someone explain to me how Data Tracker is calculating reli?

**Comment by miyamot0** [comment]
The logic for scoring is indicated in the code: https://github.com/miyamot0/DataTracker3/blob/master/reliabilityscoring.h

Specifically, the coding you are referring to is included in the "GetDurationBins" method.

The binning of responses into intervals follows the conventions of BDataPro (i.e., 10s bins by default). This is by no means the best scenario for all cases, but it was done to support comparisons with BDataPro.

Per PI logic, the interval is coding as true if the target occurs in that 10s bin (briefly or in entirety).

That's the best I can say without seeing a log file (a sample json or excel log file would help).

**Comment by ea9872** [comment]
Hi there,

Thanks for your response- I attached to this email the primary and reli
(raw and excel) files for a session 11 as well as the calculated
reliability and my own reliability calculations, even when I am using a 10
s. interval I am getting 80 percent and above agreement for both of the
keys Thanks again for your help I really appreciate it.

**Comment by miyamot0** [comment]
I do not see a file attached--I believe you must use the GitHub website to attach files (you cannot include them via email reply).

**Comment by ea9872** [comment]
011FacTraAnt_P 2.json
011FacTraAnt_P 2.xlsx
011FacTraAnt_R (Kaitlyn Hancock's conflicted copy 2020-06-29).json
011FacTraAnt_R (Kaitlyn Hancock's conflicted copy 2020-06-29).xlsx
Emma_Katie_11.xlsxEmma_Katie_11.xlsx
Personal IOA calculations Session 11.xlsx

**Comment by ea9872** [comment]
Let me know if those files worked! Thank you.

**Comment by miyamot0** [comment]
I don't that they attached? If it's easier, send to my faculty address: sgilroy1@lsu.edu

**Comment by miyamot0** [comment]
Closed (Fixed in .8)
